repos:
  - repo: local
    hooks:
      - id: go-test
        name: Go Test
        entry: go test ./...
        language: system
        types: [go]
        pass_filenames: false
      - id: go-fmt
        name: Go Format
        entry: go fmt ./...
        language: system
        types: [go]
        pass_filenames: false
      - id: go-vet
        name: Go Vet
        entry: go vet ./...
        language: system
        types: [go]
        pass_filenames: false